import Head from "next/head";
import Nav from "@/Components/Nav";
import MobileNav from "@/Components/MobileNav";
import Hero from "@/Components/Hero";
import About from "@/Components/About";
import Services from "@/Components/Services";
import Skills from "@/Components/Skills";

import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import service1 from "../public/service1.png";
import service2 from "../public/service2.png";
import service3 from "../public/service3.png";

import logo from "../public/logo.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [nav, setNav] = useState(false);
  const openNav = () => setNav(true);
  const closeNav = () => setNav(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Poenou Gaëlle Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white dark:bg-gray-900 ">
        <section>
          <MobileNav nav={nav} closeNav={closeNav} />
          <Nav openNav={openNav} />
        </section>
        <Hero />
        <About />
        <Services />
        <Skills />
        <Projects />
        <section className="py-10">
          <div className="">
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Au cours de mes études, j'ai effectué un{" "}
              <span className="text-[#496a7a]">stage</span> pratique qui m'a
              permis d'acquérir des compétences concrètes dans le domaine.
              Parallèlement, j'ai consacré du temps à des{" "}
              <span className="text-[#496a7a]">projets personnels</span>,
              démontrant ma passion pour le design et le développement.
            </p>
            <p>
              Bien que je sois un jeune diplômée, je suis animé par une volonté
              d'apprendre et de m'investir pleinement dans des projets
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                src={logo}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                src={logo}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                src={logo}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                src={logo}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                src={logo}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
