import Head from "next/head";
import Nav from "@/Components/Nav";
import MobileNav from "@/Components/MobileNav";
import Hero from "@/Components/Hero";

import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import profil from "../public/profil-removebg-preview.png";
import service1 from "../public/service1.png";
import service2 from "../public/service2.png";
import service3 from "../public/service3.png";
import logo from "../public/logo.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [nav, setNav] = useState(false);
  const openNav = () => setNav(true);
  const closeNav = () => setNav(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Poenou Gaëlle Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-20">
        {/* Section 1: Navigation */}
        <section>
          <MobileNav nav={nav} closeNav={closeNav} />
          <Nav openNav={openNav} />
        </section>
        {/* Section 2: Hero */}
        <Hero />

        <section>
          <div className="">
            <h3 className="text-3xl py-1">About me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Diplômée récemment, je me lance en tant que{" "}
              <span className="text-[#496a7a]">développeuse web</span>. À la
              recherche d'opportunités en freelance ou en tant que salarié, je
              m'engage à apporter créativité et compétences. Ma polyvalence
              s'étend du{" "}
              <span className="text-[#496a7a]">front-end au back-end</span>.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              En tant que passionnée de développement web, j'explore constamment
              de nouvelles façons d'appliquer mes{" "}
              <span className="text-[#496a7a]">compétences</span> fraîchement
              acquises.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={service1}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Développement de sites web{" "}
              </h3>
              <p className="py-2">
                Création de sites web offrant une expérience utilisateur
                optimale sur différents appareils et tailles d'écrans.
              </p>
              <h4 className="py-4 text-[#496a7a]">Mes outils </h4>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={service2}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Intégration de maquettes
              </h3>
              <p className="py-2">
                Transformation de maquettes graphiques en pages web
                interactives.
              </p>
              <h4 className="py-4 text-[#496a7a]">Mes outils </h4>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={service3}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Maintenance de sites existants
              </h3>
              <p className="py-2">
                Résolution de bugs, mise à jour de contenus et optimisation de
                la performance pour des sites déjà en ligne.
              </p>
              <h4 className="py-4 text-[#496a7a]">Mes outils </h4>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
              <p className="text-gray-800 py-1">lorem</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div className="">
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Au cours de mes études, j'ai effectué un{" "}
              <span className="text-[#496a7a]">stage</span> pratique qui m'a
              permis d'acquérir des compétences concrètes dans le domaine.
              Parallèlement, j'ai consacré du temps à des{" "}
              <span className="text-[#496a7a]">projets personnels</span>,
              démontrant ma passion pour le design et le développement.
            </p>
            <p>
              Bien que je sois un jeune diplômée, je suis animé par une volonté
              d'apprendre et de m'investir pleinement dans des projets
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                src={logo}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                src={logo}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                src={logo}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                src={logo}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                src={logo}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
